Keyac 2
MineFactory-Resource/KeyCommand pull request #2
Opened 2022-01-07 19:00 UTC by Seokhun-Yang

https://teamuni.atlassian.net/browse/KEYAC-2

ACTION: “SHIFT”, “SHIFT+SPACE”, “F”, “SHIFT+F”
* "SHIFT+SPACE" 는 제외됨. *

위 값으로 지정할 수 있게끔 하기
SHIFT 로 해두면 COMMAND: 가 SHIFT 시 실행되고 SHIFT+F 로 해두면 SHIFT+F 시 실행되고..

2022-01-07 20:55 UTC, abelbeak commented
뭔데 컨플릭트나지

2022-01-07 21:03 UTC, abelbeak commented
다음부터는 커밋 메세지와 PR제목, 내용 제대로 적으렴

2022-01-07 21:11 UTC, abelbeak commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +            }
같은 이벤트를 핸들링 하는 함수가 왜 여러개 있지?

2022-01-07 21:27 UTC, abelbeak requested changes

2022-01-07 21:27 UTC, abelbeak commented on src/main/java/net/teamuni/shiftf/Shiftf.java
>      }
어째서 하나의 이벤트를 핸들링하는 함수가 2개인가요

2022-01-07 21:27 UTC, abelbeak commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +                }
이 if문에 의미는 무엇인가요 왜 사용했나요?

2022-01-07 21:27 UTC, abelbeak commented on src/main/resources/config.yml
> +  - 'F'
Action은 하나만 가질 수 있는데 왜 리스트?

2022-01-07 21:27 UTC, abelbeak commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +        List<String> action = getConfig().getStringList("action");
하나의 액션을 왜 여러개 가져오는 구문을 썼을까요

2022-01-07 21:27 UTC, abelbeak commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +                }
이벤트가 발생할 때 마다 파일을 다시 한번 더 읽어와야 하면 낭비 아닐까

2022-01-07 21:27 UTC, abelbeak commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +    public void onPlayerToggleSneakEvent(PlayerToggleSneakEvent event) {
플레이어가 은신을 크고 끄는 이벤트를 왜 가져와서 썼나요?

2022-01-07 21:27 UTC, abelbeak commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +            }
왼손으로 아이템을 이동시키는걸 막는 구문이 없네요.
디코방에서 분명 물어보고 누가 답해준거같았는데..

2022-01-08 06:42 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/shiftf/Shiftf.java
>      }
여러가지 이벤트들을 시도해보다가 커밋 전 확인하지 못 했습니다. 수정하도록 하겠습니다.

2022-01-08 06:42 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +                }
우선 이 if문에 있는 offhand 참조 변수는 플레이어가 두 손에 있는 아이템을 맞바꾸었을 때 보조 손에 있는 아이템의 타입을 얻는 참조 변수입니다. 
결론적으로, 이 if문의 의미는 만약 주 손에서 보조 손으로 온 아이템 타입이 AIR(어떠한 아이템도 보조 손으로 오지 않았을 때)가 아니거나 AIR 일 때 config.yml에 있는 commands 들을 실행시키는 것입니다.

2022-01-08 06:42 UTC, Seokhun-Yang commented on src/main/resources/config.yml
> +  - 'F'
수정하도록 하겠습니다.

2022-01-08 06:42 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +        List<String> action = getConfig().getStringList("action");
아무 문제 없이 작동이 돼서 의심을 품지 않았던 것 같습니다. 수정하도록 하겠습니다.

2022-01-08 06:42 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +                }
낭비인 것 같습니다. 수정하도록 하겠습니다.

2022-01-08 06:42 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +    public void onPlayerToggleSneakEvent(PlayerToggleSneakEvent event) {
만약 config.yml에서 action에 'SHIFT'로 등록이 되어 있다면 앉는 이벤트를 이용하여 commands를 실행시키기 위해서입니다.

2022-01-08 06:43 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +            }
이슈 보드에 보조 손으로 아이템 이동을 막는 기능을 추가하라는 말씀이 없으셨어서 추가해야하는 줄 몰랐습니다. 추가하도록 하겠습니다.

2022-01-08 06:59 UTC, abelbeak commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +                }
왼손이 공기여도, 공기가 아니여도 똑같은걸 실행시킬거면 If가 왜 필요한지?

2022-01-08 09:39 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +                }
다시보니 이상하네요 수정하도록 하겠습니다.

2022-01-08 15:31 UTC, abelbeak commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +                }
이거 해결 안되었는데?

2022-01-08 15:37 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +                }
재수정하였습니다.

2022-01-08 23:04 UTC, abelbeak commented
잘 해결된거같긴한데 커밋 제목, 메세지 제대로좀 적어라 ㅡㅡ

2022-01-08 23:05 UTC, abelbeak commented
다른 사람들 코드리뷰하세욥

2022-01-09 05:48 UTC, Fade-Jung approved these changes

2022-01-09 08:18 UTC, kari0707 commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +                }
여러번 쓰는 코드는 메소드로 만들어두시는게 나중에 수정할 경우에도 간단하고 보기에도 깔끔합니다.

2022-01-09 08:38 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +                }
event가 하나가 아닌데 45~47 번째 줄을 메소드로 만들어 다른 메소드에 호출하여 작동할 수 있게 하는 것이 가능한가요?

2022-01-09 12:50 UTC, All298Lie commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +        event.setCancelled(true);
취소를 이 부분에서 하면 콘피그에서 설정한 액션이 아니더라도
양손 아이템을 교환하는 기능을 사용 못하지 않나요?

2022-01-09 13:03 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +        event.setCancelled(true);
수정하겠습니다.

2022-01-09 13:15 UTC, LesserJang commented on src/main/java/net/teamuni/shiftf/Shiftf.java
>          }
이러면 F키를 누를때만 이벤트 캔슬 되고 쉬프트 F키를 눌러도 이벤트 캔슬이 안될텐데..

2022-01-09 13:15 UTC, LesserJang commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +    private void PerformCommand(Player player) {
메소드 이름은 camelCase 표기법 따라서 첫글자를 소문자로 해주세요.

2022-01-09 13:15 UTC, LesserJang commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +            if (event.getPlayer().isSneaking()) {
getPlayer()로 확인하는것보다는 event.isSneaking() 을 이용하는게 더 나을것 같네요.
또 if 문 두개면 && 로 엮는거 어떤가요?
예시:
`if (action.equals("SHIFT")&&event.isSneaking()) {`

2022-01-09 13:20 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/shiftf/Shiftf.java
>          }
수정하도록 하겠습니다.

2022-01-09 13:20 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +    private void PerformCommand(Player player) {
네 알겠습니다.

2022-01-09 13:20 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +            if (event.getPlayer().isSneaking()) {
수정하도록 하겠습니다.

2022-01-09 13:34 UTC, LesserJang approved these changes

2022-01-09 13:45 UTC, All298Lie approved these changes

2022-01-09 14:36 UTC, kari0707 approved these changes

2022-01-10 11:45 UTC, abelbeak requested changes

2022-01-10 11:45 UTC, abelbeak commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +                event.setCancelled(true);
명령어를 실행한 뒤 이벤트 캔슬이 아닌
이벤트를 캔슬한 뒤 명령어를 실행해야겠죠?

2022-01-10 11:48 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +                event.setCancelled(true);
수정하겠습니다.

2022-01-10 11:59 UTC, kari0707 commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +            }
여기 결국 실행되는 부분은 같으니까 연산자 써서 if 문 다 합치면 간결해져요.

> if (action.equals("F") || (action.equals("SHIFT+F") && event.getPlayer().isSneaking())) {

2022-01-10 12:01 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +            }
수정하도록 하겠습니다.

2022-01-11 08:23 UTC, abelbeak commented
이거 다들 최종 확인하고 리뷰해주세요

2022-01-11 08:24 UTC, abelbeak approved these changes

2022-01-11 12:07 UTC, All298Lie approved these changes

2022-01-12 12:11 UTC, Fade-Jung approved these changes

2022-01-13 04:45 UTC, LesserJang approved these changes

2022-01-13 08:26 UTC, merged