명령어 PlaceHolderAPI 지원 추가하기
MineFactory-Resource/KeyCommand pull request #6
Opened 2022-03-06 16:08 UTC by Seokhun-Yang

2022-03-06 17:44 UTC, Fade-Jung approved these changes

2022-03-06 21:55 UTC, kari0707 approved these changes

2022-03-06 22:49 UTC, All298Lie requested changes

2022-03-06 22:49 UTC, All298Lie commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +            player.performCommand(PlaceholderAPI.setPlaceholders(player, playerCommand).substring(9));
플러그인에서 PlaceholderAPI 지원을 하게되면서 사용은 선택적으로 가능하게 해두셨는데,
코드를 보면 PlaceholderAPI 사용여부를 상관없이 모두 PlaceholderAPI가 지원되야 실행이 되도록 되어있습니다.
PlaceholderAPI를 사용 중일 경우에만 지원된 기능을 사용하게 바꾸셔야 될 것 같습니다.

2022-03-07 00:07 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/shiftf/Shiftf.java
> +            player.performCommand(PlaceholderAPI.setPlaceholders(player, playerCommand).substring(9));
수정하도록 하겠습니다.

2022-03-07 13:24 UTC, LesserJang approved these changes

2022-03-07 13:25 UTC, merged